### ISSUE TITLE
New metrics to calculate for GUI output

### ISSUE THREAD

**Issue by jordanyx** [SchmollerLab/Cell_ACDC#13]
**Is your feature request related to a problem? Please describe.**
I'm often interested in metrics like the coefficient of variation of a fluorescence signal _over space_ within a single cell, which should be easily calculated given mask and fluo channel info, but isn't currently part of the output of the main CellACDC GUI.

**Describe the solution you'd like**
A way to add the aforementioned coefficient of variation metric, as well as other calculations that might be relevant depending on the experiment. As a stretch goal, it would be neat to have a standard set of calculations that users can select from when saving the data from a position (so one could unselect unimportant ones to save time), as well as the ability to introduce custom calculations.

**Comment by ElpadoCan** [comment]
Hi Jordan, I just released `v1.2.4rc7` that contains the fix for this. 

You can now add custom metrics that takes the signal and the background value as input and returns whatever calculation you want to do with it. You just need to write the function and put it into the `<user-path>/acdc-metrics`. I added some instructions in the new menu on the menubar on the top of the main GUI called `Measurements`

In that menu there is also a new functionality called `Set measurements...` that will allow you to select which metrics you want to save, and for each metric there is an info button with a description of the specific metric.

Update with `pip install --upgrade cellacdc` and let me know if it works, thanks!

**Comment by jordanyx** [comment]
Hi Francesco, this menu appears to be working, and seems straightforward to use. I'll let you know if I find any issues later. Thanks for adding this!

**Comment by ElpadoCan** [comment]
Hi Jordan, I just thought now that I might have changed something with the new Set measurements function that broke the downstream analysis, I will fix it today, thanks!

**Comment by jordanyx** [comment]
Hi Francesco,

Quick question about the CV custom measurement--does it calculate the CV after performing background subtractions? If so, does it use autoBkgr or dataPrepBkgr?

More broadly, I'm trying to quantify nuclear localization of a protein using the CV as a proxy (which has worked in the past), and wanted to make sure the CV calculated in this instance is still usable the same way.

Thanks!

**Comment by ElpadoCan** [comment]
Hi Jordan, so for the CV you can actually choose what to do with the background signal. If you go to your user path (something like C:\Users on Windows) there is a folder called `acdc-metrics` and inside that folder there is a python script called `CV.py`. You can see this folder path if you go to the `Measurements --> Add custom metric` menu on the top of the GUI, where you will get some instructions. Inside the `CV.py` file you will find the `CV` function which has the arguments called `correct_with_bkgr=False` and `which_bkgr='auto'`. With these arguments, you can choose whether you want to correct the signal using the background value and which background you want to use (anything different from 'auto' will use the dataPrepBkgr value).

I hope it's clear enough, thanks.

**Comment by jordanyx** [comment]
Got it, thank you!

**Comment by jordanyx** [comment]
Hi Francesco,

I tried creating a custom metric that is basically CV_dataPrep_Bkgr; basically copy-pasted CV.py and changed a few arguments, and also updated the function name within the script, as described. It shows up correctly when I set measurements in the GUI, but it's not showing up in overall_df once I load the data into jupyter lab.  Is there something else I need to do to get it to make it to actually calculate the metric?

**Comment by ElpadoCan** [comment]
Hi Jordan, the 1D array is a vector with the signal from all the pixels of each cell, so no it is not a single number but the entire distribution. It's a 1D array because when you index a NumPy array with a boolean mask (i.e., the segmented cell) the output is a flattened 1D array.

Anyway, I will look into how to get the metric into overall_df now, I keep you updated.

**Comment by ElpadoCan** [comment]
Hi Jordan, so I just did some tests and, after creating the CV_dataPrep_Bkgr.py as you described, I saved the metrics in the GUI and I got a new column in the `acdc_output.csv` file called `Dia_Ph3_CV_dataPrepBkgr` (where my channel is called Dia_Ph3) as expected. When I then loaded the data into jupyter-lab I get the same column in the `overall_df` table, so everything seems to work fine on my side.

Did you recalculate the metrics in the GUI after creating your `CV_dataPrep_Bkgr.py` file? Can you check if after saving the metrics you get the new column in the acdc_output.csv file? Thanks

**Comment by jordanyx** [comment]
Hi Francesco, turns out I had to restart CellACDC to get it to work! Apologies for wasting your time; I must have missed it if it's in the instructions. Thanks!

And the CV calculation makes sense now, thanks! I don't suppose you also saw my email regarding my specific data?

**Comment by ElpadoCan** [comment]
Hi Jordan, absolutely no problem. In general, you always have to restart Cell-ACDC to get the updates. That's because Python loads the libraries only when you run it and you need to restart to load new stuff.

For the background signal, you are right, the doc string is wrong, it is a single numeric value. In any case, it works like you said, when you subtract a single numeric value to a numpy array that value is subtracted to each element of the array. 

For the values that you can use in the custom metrics, as of now, you can only manipulate the 1D array signal, you cannot combine it with other columns. However, I will keep this issue open and I can implement that feature. I will keep you updated.

For your email, I actually saw it, downloaded your sample data and started having a look at it, but I forgot to reply :D, sorry about that.

**Comment by jordanyx** [comment]
Thanks again for helping me make sense of my data! And yes, I'd love to be able to work with other columns for custom metrics. In particular, since my signal to noise is so low, I need to do autofluorescence corrections where possible. I specifically want to use the autofluorescence-corrected signal to calculate the CV, so I want to apply the AF correction _before_ the CV calculation; not sure what order ACDC's custom metrics are calculated in, but maybe this gives you an idea of how it can be implemented.

**Comment by jordanyx** [comment]
Wonderful, thank you! I'll give it a try and let you know if I run into any issues.

Also just wanted to say, I appreciate the aesthetic upgrades to the GUI too!

**Comment by jordanyx** [comment]
Hi Francesco, the custom and combined metrics stuff is working wonderfully!

What is the best way to edit combined measurements after the fact? For instance, I tried defining something called 'mCitrine_sum_AFcorrected', but when it saved it appended the channel name again so it became 'mCitrine_mCitrine_sum_AFcorrected'. Changing the name in the .ini file didn't work, so I deleted the .ini files and redid it.

**Comment by ElpadoCan** [comment]
Hi Jordan, you are right, if you put the `mCitrine` in the name and then you only use columns from the `mCitrine` signal that Cell-ACDC appends the `mCitrine` again. I did not think of that possibility, it's an easy fix anyway.

However, you don't need to prepend `mCitrine` if you use only measurements from `mCitrine` channel because Cell-ACDC will recognise that you are asking for another mCitrine-specific measurement and it will prepend the channel. If instead, you use a mix of channels that the name stays what you requested. 

I will add a checkpoint anyway that will recognise that you already prepended the channel name. Thanks for finding that!

**Comment by jordanyx** [comment]
Got it, that makes sense!

Any insights on the second issue? I.e. using a custom measurement defined for one position/experiment for another?

**Comment by ElpadoCan** [comment]
Oh sorry, I misread your issue.

When you say that you are defining a custom measurement in one position you mean a combined measurement right? This is just to be sure what you are referring to. I call "custom" measurement a measurement defined by a python script in the `acdc-metrics`, while a combined measurement is defined through the menu `Measurements --> Add combined measurement...`.

**Comment by ElpadoCan** [comment]
Hi Jordan, so I did some tests and everything seems to work as expected, however, I understand that it is not clear at all how it works. So here is what is supposed to happen:

Let's assume you have a channel called `mCitrine`. So you open the Position with this channel and define a combined measurement as `mytest = mCitrine_sum - mCitrine_mean`. Now, this equation is saved in the specific Position folder in the file that ends with `custom_combine_metrics.ini`, but it's also saved in your user folder in the folder called `acdc-metrics` (for example `C:\Users\jordan\acdc-metrics`).

When you re-open the same Position, cell-acdc will find the `custom_combine_metrics.ini` and add `mytest` to the list of saved metrics.

When you open another Position, cell-acdc will check if there is a file in the `user_folder/acdc-metrics` folder called `combine_metrics.ini` and, if the channel mCitrine is also present in this newly opened position, it will automatically add this combined metric to the list of saved metrics. 

However, if you open a Position that does not have the mCitrine channel then acdc will ignore the previously saved metric `mytest`, since this metric was specific to mCitrine.

When you create a combined metric that is the result of combining multiple channels, for example `my_mixed_test = mCitrine_sum - GFP_sum`, then cell-acdc will save as usual but to the field in the .ini file called `[mixed_channels_equations]`. These measurements will then be added to the list of saved metrics for ANY other Position that you open because the mixed channel equations are independent of the channel name (the example above would be stored as `my_mixed_test = channel_1_sum - channel_2_sum`, where 1 and 2 are determined by alphabetical order). 

So in general, if you always want to have the same channel-specific equation, then you need to have all the Positions with the exact same channel name.

The reason why it works like this is that I personally work with many different channel names depending on the fluorophore or experiment that I do, so, usually, I don't want the same combined measurement that I had for mNeon when I open a completely different experiment that used tdTomato for example. 

Note that you can always choose to not save a specific combined measurement by unchecking it in the `Set measurements...` dialogue.

I hope it's clear and let me know if you think it should behave differently. Cheers!

**Comment by jordanyx** [comment]
Hi Francesco, thanks for the explanation! What you described does make sense, but somehow it doesn't seem to work on my data for some reason!

Long story short, I defined two parameters: one that falls under the "mixed channel" category, and one that should apply to one channel. I defined and saved it for one position, which worked; I can open acdcoutputs.csv and both fields are in there.

When I open another position within the same movie, so same channel names and everything, I can see the new metrics in the right places under "set measurements"; one under mixed, one under the specific channel. But when I actually save it doesn't appear in my acdcoutput.csv for the second position.

I first saw the issue in rc29, but just checked in rc31 and it's still happening.

**Comment by jordanyx** [comment]
On a somewhat related topic, is it possible to use area, volume, etc. and other metrics when writing a python file under custom metrics? I think that might actually be easier to use for the most part than the "combined measurements", since it's possible to leave comments and such.

**Comment by ElpadoCan** [comment]
Hi Jordan, now I got your issue.

I opened two new issues #

**Comment by ElpadoCan** [comment]
Hi Jordan, I released `v1.2.4rc32` which has a fix for the bug described at issue #101 

Combined measurements defined at one Position should also be saved in any other Position (if they have the same channel name).

Please update with `pip install --upgrade cellacdc` and let me know if it works! Cheers

**Comment by jordanyx** [comment]
Hi Francesco, I tested it out and it looks like the channel-specific "combined measurement" feature is saving correctly now. However, at the same time it looks like the "mixed channels combined measurement" still isn't saving.

**Comment by ElpadoCan** [comment]
> Hi Francesco, I tested it out and it looks like the channel-specific "combined measurement" feature is saving correctly now. However, at the same time it looks like the "mixed channels combined measurement" still isn't saving.

Hi Jordan, I released `v1.2.4rc33` which has a fix for this issue.

Please update with `pip install --upgrade cellacdc` and let me know if it works, thanks!

**Comment by jordanyx** [comment]
Hi Francesco, no idea what's going on but the "mixed channels combined measurement" I defined still isn't saving for any position besides the one it was originally defined for. Would it help if I provided any files?

I also noticed that the channel-specific "channel measurement" doesn't always save either--haven't figured out what the pattern is, but I was testing it on a channel that hadn't been complete tracked or m-b paired. Maybe that makes a difference? (The "mixed channel combined measurement" wasn't saving for any channel, regardless of complete tracking/m-b assignment, so I think something else might be going on here.)

**Comment by ElpadoCan** [comment]
Hi Jordan, I think sharing the data would help a lot sure. Can you send me a Position where you defined the "mixed channels combined measurement" and one where the same measurement doesn't get saved? 

The complete tracked or paired shouldn't make any difference. Could you also share a Position where the channel measurement is saved and one where it is not saved? Thanks!

**Comment by jordanyx** [comment]
Hi Francesco, here's the experiment I was testing stuff in. I defined two new metrics: one called {ch_name}_test (single-channel combined measurement, a nonsensical quantity), and one called mCitrineFFC_AF_deduction (mixed channel combined measurement, but actually only uses constants and cell volume vox). Both of these were initially defined in Position 1. I have full seg/track/m-b pairing for Positions 1 and 2, but not for 6.

Last time I was testing, this is what I saw (and should be reflected in the acdc_output.csv for each position):
Position 1: both metrics save (test and deduction)
Position 2: only "test" saves, somehow "deduction" doesn't
Position 6: neither saves

https://drive.google.com/file/d/1ofm1XjEh60TartfVohpqhSmrozkc7Ig-/view?usp=sharing

**Comment by ElpadoCan** [comment]
Hi Jordan, I am doing some tests and still haven't fixed the issue, but I need some information from you first. 

When I open your Position_2 it doesn't save the deduction metric, but that is expected because in my user folder inside the folder `acdc-metrics` I don't have the deduction measurement defined because it was defined by you. In this case, when I open Position_2 it will not find this measurement from my user folder.

Could you please check if you have the deduction measurement defined in your user folder inside the `acdc-metrics/combine-metrics.ini` file? Could you please send me also that file so that I can do tests in your same situation? 
Thanks

**Comment by ElpadoCan** [comment]
Hi Jordan, in the end, it was a stupid bug :(.

I took the opportunity to improve the feature a little bit. Now I added that it also scans all the other Positions in the same experiment and it automatically read combined metrics defined in other Positions (and not only the ones that were saved in the user folder).

This way you can take the Positions folder with you on another computer (where you did not define measurements) and all of the Positions will have the same measurements despite the fact there are no measurements defined in the user path.

I hope it makes sense! 

Anyway, I released `v1.2.4rc34` which has the fix plus the improvement. Please update with `pip install --upgrade cellacdc` and let me know if it works.  Thank you for your patience!

**Comment by jordanyx** [comment]
Hi Francesco, sorry about the delay, I was traveling this weekend. Thanks for the fix!
