### ISSUE TITLE
manualBkgr error when re-saving measurements

### ISSUE THREAD

**Issue by jordanyx** [SchmollerLab/Cell_ACDC#394]
### Description:

I was trying to re-save measurements on some movies that had been completely analyzed in an older version of ACDC (v1.2.4; now updated to v1.4.0), and got the below error:

==============================
Traceback (most recent call last):
  File "C:\Users\jyxiao\anaconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 699, in run
    acdc_df = self.addMetrics_acdc_df(
  File "C:\Users\jyxiao\anaconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 421, in addMetrics_acdc_df
    df = measurements.add_foregr_metrics(
  File "C:\Users\jyxiao\anaconda3\envs\acdc\lib\site-packages\cellacdc\measurements.py", line 1424, in add_foregr_metrics
    foregr_arr = foregr_data[how]
KeyError: 'manualBkgr'
******************************

Log file below:

[2023-08-15_13-23-23_acdc_gui_554a4fc1-69b7-4a35-adeb-19e47a6a2242_stdout.log](https://github.com/SchmollerLab/Cell_ACDC/files/12352774/2023-08-15_13-23-23_acdc_gui_554a4fc1-69b7-4a35-adeb-19e47a6a2242_stdout.log)

### Way to reproduce:

Open old movie/position, Ctrl-Alt-S or save from File menu, select Yes for save measurements.

I've confirmed it happens both on my data and someone else's. If it would be useful, I can provide a sample of my data where the error happens. It doesn't seem to happen for movies analyzed start-to-finish in the updated version (1.4.0).

### Terminal output:

```Shell
13:24:44 - File "gui.py", line 362:
{'Phase': {'Phase_autoBkgr_bkgrVal_mean': ('autoBkgr', 'mean', ''),
           'Phase_autoBkgr_bkgrVal_median': ('autoBkgr', 'median', ''),
           'Phase_autoBkgr_bkgrVal_q05': ('autoBkgr', 'q05', ''),
           'Phase_autoBkgr_bkgrVal_q25': ('autoBkgr', 'q25', ''),
           'Phase_autoBkgr_bkgrVal_q75': ('autoBkgr', 'q75', ''),
           'Phase_autoBkgr_bkgrVal_q95': ('autoBkgr', 'q95', ''),
           'Phase_dataPrepBkgr_bkgrVal_mean': ('dataPrepBkgr', 'mean', ''),
           'Phase_dataPrepBkgr_bkgrVal_median': ('dataPrepBkgr', 'median', ''),
           'Phase_dataPrepBkgr_bkgrVal_q05': ('dataPrepBkgr', 'q05', ''),
           'Phase_dataPrepBkgr_bkgrVal_q25': ('dataPrepBkgr', 'q25', ''),
           'Phase_dataPrepBkgr_bkgrVal_q75': ('dataPrepBkgr', 'q75', ''),
           'Phase_dataPrepBkgr_bkgrVal_q95': ('dataPrepBkgr', 'q95', ''),
           'Phase_manualBkgr_bkgrVal_mean': ('manualBkgr', 'mean', ''),
           'Phase_manualBkgr_bkgrVal_median': ('manualBkgr', 'median', ''),
           'Phase_manualBkgr_bkgrVal_q05': ('manualBkgr', 'q05', ''),
           'Phase_manualBkgr_bkgrVal_q25': ('manualBkgr', 'q25', ''),
           'Phase_manualBkgr_bkgrVal_q75': ('manualBkgr', 'q75', ''),
           'Phase_manualBkgr_bkgrVal_q95': ('manualBkgr', 'q95', '')}}
==============================

====================================
Traceback (most recent call last):
  File "C:\Users\jyxiao\anaconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 699, in run
    acdc_df = self.addMetrics_acdc_df(
  File "C:\Users\jyxiao\anaconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 421, in addMetrics_acdc_df
    df = measurements.add_foregr_metrics(
  File "C:\Users\jyxiao\anaconda3\envs\acdc\lib\site-packages\cellacdc\measurements.py", line 1424, in add_foregr_metrics
    foregr_arr = foregr_data[how]
KeyError: 'manualBkgr'

====================================
******************************
13:24:44 - File "gui.py", line 362:
{'Phase': {'Phase_autoBkgr_bkgrVal_mean': ('autoBkgr', 'mean', ''),
           'Phase_autoBkgr_bkgrVal_median': ('autoBkgr', 'median', ''),
           'Phase_autoBkgr_bkgrVal_q05': ('autoBkgr', 'q05', ''),
           'Phase_autoBkgr_bkgrVal_q25': ('autoBkgr', 'q25', ''),
           'Phase_autoBkgr_bkgrVal_q75': ('autoBkgr', 'q75', ''),
           'Phase_autoBkgr_bkgrVal_q95': ('autoBkgr', 'q95', ''),
           'Phase_dataPrepBkgr_bkgrVal_mean': ('dataPrepBkgr', 'mean', ''),
           'Phase_dataPrepBkgr_bkgrVal_median': ('dataPrepBkgr', 'median', ''),
           'Phase_dataPrepBkgr_bkgrVal_q05': ('dataPrepBkgr', 'q05', ''),
           'Phase_dataPrepBkgr_bkgrVal_q25': ('dataPrepBkgr', 'q25', ''),
           'Phase_dataPrepBkgr_bkgrVal_q75': ('dataPrepBkgr', 'q75', ''),
           'Phase_dataPrepBkgr_bkgrVal_q95': ('dataPrepBkgr', 'q95', ''),
           'Phase_manualBkgr_bkgrVal_mean': ('manualBkgr', 'mean', ''),
           'Phase_manualBkgr_bkgrVal_median': ('manualBkgr', 'median', ''),
           'Phase_manualBkgr_bkgrVal_q05': ('manualBkgr', 'q05', ''),
           'Phase_manualBkgr_bkgrVal_q25': ('manualBkgr', 'q25', ''),
           'Phase_manualBkgr_bkgrVal_q75': ('manualBkgr', 'q75', ''),
           'Phase_manualBkgr_bkgrVal_q95': ('manualBkgr', 'q95', '')}}
==============================

====================================
Traceback (most recent call last):
  File "C:\Users\jyxiao\anaconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 699, in run
    acdc_df = self.addMetrics_acdc_df(
  File "C:\Users\jyxiao\anaconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 421, in addMetrics_acdc_df
    df = measurements.add_foregr_metrics(
  File "C:\Users\jyxiao\anaconda3\envs\acdc\lib\site-packages\cellacdc\measurements.py", line 1424, in add_foregr_metrics
    foregr_arr = foregr_data[how]
KeyError: 'manualBkgr'

====================================
Almost done...
Saved data until frame number 121
```

### Version information:

```Shell
Cell-ACDC version: 1.4.0
```

**Comment by ElpadoCan** [comment]
Hi Jordan, I'm on holiday for the next 2 weeks but I will definitely find some time to look into this. The problem is caused by a new feature where one can set the background with the same ROI of an object. Apparently it causes this error with your data. I will keep you updated, thank you for your patience!

Cheers
Francesco

**Comment by RoussouRia** [comment]
Hi Jordan, 
By going to 'Measurements' -> 'Set measurements' and un-clicking the 'manualBkgr'-related boxes, you can save without any issue! (For example, I excluded the measurements 'BF_mean_manualBkgr' and 'BF_amount_manualBkgr'). 
Hope this helps!

Cheers, Ria

**Comment by ElpadoCan** [comment]
Thanks @RoussouRia for reporting this. This means that the error is bypassed and only reported while all other metrics should be successfullly saved.

**Comment by jordanyx** [comment]
Thanks for the tip! Unfortunately it still didn't work for me for some reason. In fact, even when I tried unchecking everything except for sum/mean/median/max/min, I got the following:

==============================
Traceback (most recent call last):
  File "C:\Users\jyxiao\anaconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 699, in run
    acdc_df = self.addMetrics_acdc_df(
  File "C:\Users\jyxiao\anaconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 421, in addMetrics_acdc_df
    df = measurements.add_foregr_metrics(
  File "C:\Users\jyxiao\anaconda3\envs\acdc\lib\site-packages\cellacdc\measurements.py", line 1450, in add_foregr_metrics
    foregr_arr = foregr_data[how]
KeyError: 'autoBkgr'
******************************

Note that this time it's autoBkgr, not manualBkgr.

(Kind of related, I've noticed that even when I uncheck a bunch of measurements, every time I open up the "set measurements" window, they're all re-checked; is this expected behavior? I would have thought it would remember which ones I checked/unchecked within a given session.)

Also, while the save function seemingly bypasses the error and runs to completion, when I check the acdc output CSV nothing has been saved over, and the file's "date modified" is still the same as from months ago when I last saved it (how I noticed in the first place).

Last thing to add: this all began because I tried using the "Compute measurements on multiple experiments" function, and I ran into this error very early in that process:
```
Launching utility "Compute measurements for one or more experiments..."
Asking to select experiment folders...
------------------------------
Processing experiment n. 1/1, Position_1 (1/3)
Processing experiment n. 1/1, Position_2 (2/3)
Processing experiment n. 1/1, Position_3 (3/3)
Traceback (most recent call last):
  File "C:\Users\jyxiao\anaconda3\envs\acdc\lib\site-packages\cellacdc\utils\compute.py", line 138, in workerAskStopFrame
    win = apps.stopFrameDialog(posDatas, parent=self)
  File "C:\Users\jyxiao\anaconda3\envs\acdc\lib\site-packages\cellacdc\apps.py", line 11552, in __init__
    _val = posData.segmSizeT
AttributeError: 'loadData' object has no attribute 'segmSizeT'
```
No associated error window, but this is what printed in terminal. I'm not sure if this error is related, but thought might be worth mentioning. If it's a separate issue I can start a new one on Github.

I've attached the new log file as well.

[2023-08-16_14-05-48_acdc_gui_7a94a708-128e-4071-b6b5-8d57b6ecd8a3_stdout.log](https://github.com/SchmollerLab/Cell_ACDC/files/12363664/2023-08-16_14-05-48_acdc_gui_7a94a708-128e-4071-b6b5-8d57b6ecd8a3_stdout.log)

As always, thanks for the timely assistance!

**Comment by ElpadoCan** [comment]
> Note that this time it's autoBkgr, not manualBkgr. 

Yeah the fact that it is `autoBkgr` is weird, I will definitely look into it soon. I will keep you updated.

> Last thing to add: this all began because I tried using the "Compute measurements on multiple experiments" function, and I ran into this error very early in that process:

Yeah I noticed this one recently. I actually already fixed it on the developer version but I didn't release it on PyPi yet. Next release will have this fix too, thanks for reporting!

**Comment by ElpadoCan** [comment]
Hi @jordanyx and @RoussouRia, I just released `v1.4.1` with a fix for this. 

For @jordanyx you can upgrade with the command `pip install --upgrade cellacdc`

For @RoussouRia you can upgrade with the usual `git pull` command.

Let me know if it works, thanks!

**Comment by jordanyx** [comment]
Hi Francesco, I think it's partially fixed! Now when I uncheck all the metrics besides sum/mean/median/min/max, it saves fine. However, when I try to save all the other quantities I still get this error:

==============================
Traceback (most recent call last):
  File "C:\Users\jyxiao\anaconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 698, in run
    acdc_df = self.addMetrics_acdc_df(
  File "C:\Users\jyxiao\anaconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 420, in addMetrics_acdc_df
    df = measurements.add_foregr_metrics(
  File "C:\Users\jyxiao\anaconda3\envs\acdc\lib\site-packages\cellacdc\measurements.py", line 1451, in add_foregr_metrics
    foregr_arr = foregr_data[how]
KeyError: 'autoBkgr'
******************************

I also get the following when I try to do the multi-experiment/position save:

==============================
Traceback (most recent call last):
  File "C:\Users\jyxiao\anaconda3\envs\acdc\lib\site-packages\cellacdc\workers.py", line 934, in run
    acdc_df = addMetrics_acdc_df(
  File "C:\Users\jyxiao\anaconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 389, in addMetrics_acdc_df
    autoBkgr_masks = measurements.get_autoBkgr_mask(
  File "C:\Users\jyxiao\anaconda3\envs\acdc\lib\site-packages\cellacdc\measurements.py", line 797, in get_autoBkgr_mask
    autoBkgr_mask = _mask_0valued_pixels_from_alignment(
  File "C:\Users\jyxiao\anaconda3\envs\acdc\lib\site-packages\cellacdc\measurements.py", line 1100, in _mask_0valued_pixels_from_alignment
    if posData.dataPrep_ROIcoords is not None:
AttributeError: 'loadData' object has no attribute 'dataPrep_ROIcoords'
******************************

It definitely gets farther than it used to. Here's the log file:
[2023-08-18_14-32-37_utils.computeMeasurements_df752b7a-fd40-4349-8332-d5578883e21b_stdout.log](https://github.com/SchmollerLab/Cell_ACDC/files/12384102/2023-08-18_14-32-37_utils.computeMeasurements_df752b7a-fd40-4349-8332-d5578883e21b_stdout.log)

Again, sorry to bug on you on your holiday. Thanks so much for taking the time!

**Comment by ElpadoCan** [comment]
Hi Jordan, could you please share the position folder with me? It's probably the fastest way to fix this.

You can share it with my google drive email padovaf@tcd.ie or use the cloud of your choice. Thanks!

Cheers
Francesco

**Comment by jordanyx** [comment]
Of course! Here's the google drive folder, you should have access now. Let me know if it doesn't work.

https://drive.google.com/drive/folders/18dwdvtQfKFZatk250kPZuDtCFJe-6fvs?usp=drive_link

The acdc_output CSV was updated today as I was testing the GUI save using only sum/mean/median/min/max for a single channel. It didn't get updated when I tried the other stuff I mentioned (e.g. bulk experiment saving, or saving with any of the bkgr quantities).

**Comment by ElpadoCan** [comment]
Hi Jordan, I just released `v1.4.2`. With this version, I could save all metrics for all channels using your test position. 

To upgrade, run the command `pip install --upgrade cellacdc`. Let me know if it works, thanks!

**Comment by ElpadoCan** [comment]
I actually released `v1.4.3` because I forgot to test the measurements utility which was still giving the other error you reported. That should be fixed too. Let me know how it goes, thanks!

**Comment by jordanyx** [comment]
Hey Francesco, for some reason it's still not working on my end, and I seem to be getting the same error for the single position save on the GUI:
==============================
Traceback (most recent call last):
  File "C:\Users\jyxiao\anaconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 700, in run
    acdc_df = self.addMetrics_acdc_df(
  File "C:\Users\jyxiao\anaconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 422, in addMetrics_acdc_df
    df = measurements.add_foregr_metrics(
  File "C:\Users\jyxiao\anaconda3\envs\acdc\lib\site-packages\cellacdc\measurements.py", line 1451, in add_foregr_metrics
    foregr_arr = foregr_data[how]
KeyError: 'autoBkgr'
******************************

Log file here: 
[2023-08-20_13-06-21_acdc_gui_8148a722-32fc-4e85-a518-ea978185863e_stdout.log](https://github.com/SchmollerLab/Cell_ACDC/files/12389101/2023-08-20_13-06-21_acdc_gui_8148a722-32fc-4e85-a518-ea978185863e_stdout.log)

In the multi-position save, I also noticed a line that popped up saying something about segmentation masks being empty: "All selected positions in the experiment folder 220630_JX_MS380_2ng-uL-aTc_4hr-on_8hr-off have EMPTY segmentation mask. Metrics will not be saved."

Maybe it's related? I know the mask isn't empty because I can open all of these positions in the GUI, so not sure why that line is appearing. It's the same movie as the one position I shared with you.

Second log file: 
[2023-08-20_13-10-28_utils.computeMeasurements_cf80bc06-c5a4-4d1e-b92b-dd0ada851b4d_stdout.log](https://github.com/SchmollerLab/Cell_ACDC/files/12389111/2023-08-20_13-10-28_utils.computeMeasurements_cf80bc06-c5a4-4d1e-b92b-dd0ada851b4d_stdout.log)

If it helps, this the version of things I have:
Python 3.9.12
Qt 5.15.2
ACDC 1.4.3

Please let me know if there's anything else I can send that would help.

**Comment by ElpadoCan** [comment]
I kind of imagined this would happen because I did not change anything specific to this error in the newest version. This is because the position you sent me worked just fine on my system so there is something else going on.

Something that I can say is that according to the log file you loaded a position with filenames 

`220630_JX_MS380_2ng-uL-aTc_4hr-on_8hr-off`

While the position you shared with me has a filename like `220630_JX_MS380_2ng-uL-aTc_pos04_g_s1_acdc_output.csv`

Are you sure you shared the right position folder?

**Comment by ElpadoCan** [comment]
Disregard what I said I saw the wrong text.

I'm quite confused at this point, there might be something going on with the versions of the packages you have.

The only way forward I see is that I try myself directly on your system with Teamviewer. I will send you an email where we can set a date and time. Would that work for you?

**Comment by jordanyx** [comment]
Oh that's interesting! I think what happened for that experiment was I changed the name of the experiment folder after all the sub-files were generated. I never noticed it earlier, so it must not have caused problems in the older version.

I tested the GUI save on another experiment where the filenames and experiment name are the same and it gave the same error, so I have a feeling it's not to do with the file names.

In any case, I'm happy to try the Teamviewer thing; sorry it's become so much trouble. I've responded to the email.

**Comment by ElpadoCan** [comment]
I'm trying to understand what could be different on your system and I'm thinking of custom metrics. Do you have any custom metric that contains the words `autoBkgr` or `amount`? Could you please send me a screenshot of the "Set measurements" window? Thanks

**Comment by ElpadoCan** [comment]
Actually, I should have read the log file more carefully. The issue seems to be caused by a custom metric! It must have a name with a pattern that I never thought could have been a problem. Let me know what custom metrics you have, thanks!

**Comment by jordanyx** [comment]
![custom metrics](https://github.com/SchmollerLab/Cell_ACDC/assets/99368623/8631b597-7290-4903-a518-85e5d4e13d7f)

Here are my custom metrics. When I unchecked them everything saved fine, so you must be right!

**Comment by ElpadoCan** [comment]
That's it! Having both `CV.py` AND `CV_autoBkgr.py` causes that issue! Crazy coincidence that I never thought about. You can simplu change the name of `CV_autoBkgr.py` to `CV_auto_bkgr.py` or whatever is not with pattern `metric_autoBkgr.py`.

In the next version I will think of a better solution for this. Let me know if my hypothesis is true thanks!

**Comment by jordanyx** [comment]
I changed the name to CV_auto_bkgr.py (both file name and within the function itself) and got the following:

==============================
Traceback (most recent call last):
  File "C:\Users\jyxiao\anaconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 700, in run
    acdc_df = self.addMetrics_acdc_df(
  File "C:\Users\jyxiao\anaconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 422, in addMetrics_acdc_df
    df = measurements.add_foregr_metrics(
  File "C:\Users\jyxiao\anaconda3\envs\acdc\lib\site-packages\cellacdc\measurements.py", line 1451, in add_foregr_metrics
    foregr_arr = foregr_data[how]
KeyError: 'auto'
******************************

Luckily I don't really need this custom metric right now, so I'll just move it out of the folder or now. I'm curious, the multi-save works too as long as I uncheck that. Do you know why the custom metric would cause it to say the segmentation mask is empty?

**Comment by jordanyx** [comment]
Ah, I see! That makes sense, I'll do as you say.

Once again, thanks for taking the time to help even though you're on holiday! I'm glad figured it out!

Should I leave the issue open for now?

**Comment by ElpadoCan** [comment]
No problem at all, I'm happy we find out about this edge case. Yeah leave it open I will reference it in the next release. Thanks!

**Comment by ElpadoCan** [comment]
Hi Jordan, I just released `v1.4.5` where I fixed the issue we discussed. I also took the opportunity to make the set measurements window to remember the selection within the same session, as you suggested.

Let me know if everything works as expected thanks!

**Comment by jordanyx** [comment]
My custom metrics are working again, and the unchecked measurements stay as such. I think everything is working! Thanks for the fixes!
